### ISSUE TITLE
Bug: Incorrect proficiency listing

### ISSUE THREAD

**Issue by bikerjp** [jcolson/dndvault-bot#440]
Here is the public [link](https://www.dndbeyond.com/profile/Marak/characters/48035109) I have to a triple class character and the image below is the result of the /show command for him. It incorrectly contains the Saving Throw and the generic 'choose skill' proficiencies for my 2nd and 3rd class. 

Also remove any duplicate proficiencies. 

![image](https://user-images.githubusercontent.com/81335165/133908028-972d25dc-c510-46f4-87f3-dc4514335463.png)

**Comment by jcolson** [comment]
need to compare if the character is multiclassed and availableToMulticlass is false, then remove those proficiencies

**Comment by jcolson** [comment]
<img width="133" alt="image" src="https://user-images.githubusercontent.com/2362647/135258375-9d3ac534-3da3-4ac2-9046-11d6f1f491e5.png">
