### ISSUE TITLE
Only rolling d20

### ISSUE THREAD

**Issue by LordHebi** [jcolson/dndvault-bot#500]
I try to use the dice roller and it only rolls a d20 no matter what I put in

**Comment by jcolson** [comment]
i don't see an issue with either the prefix command or the slash command at this time:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/2362647/171685920-2e3b55e8-028c-41b8-8ad5-860597aaf0b8.png">

which are you using?  if you are using the slash command, make sure to fill out the 'notation' optional parameter with the dice formula notation that you with to be using (look at the bottom of the screenshot)

**Comment by jcolson** [comment]
i'm going to close this for now, please let me know if you are still experiencing issues.
